### ISSUE TITLE
Don't save in database

### ISSUE THREAD

**Issue by Lou47** [joshp23/YOURLS-Expiry#14]
Hi,

Very weird, it's like the plugin don't save informations in database :

- when I create a link with "counter", none information in database
- when I change a link already created, it's just the "code" of the link which is written in database, not 'count' (and with timer, none information in database)

**Comment by Lou47** [comment]
It's okay, my HTTP Headers Security blocked them, so I modified that

**Comment by joshp23** [comment]
Ah, good find. Please consider detailing the required change, I'll add it to the README.

**Comment by Lou47** [comment]
Oh yeah, actually, my Header Content-Security-Policy was on "default-src https://www.sho.rt" (default-src, script-src, frame-ancestors, form-action)
but I enforce my url to https://sho.rt without "www." so it didn't work.
I changed for default-src and all others to https://sho.rt.

It's a beginner error ahahah :) I use HTTP Security Header for 2 weeks.
