### ISSUE TITLE
links not expiring on YOURLS 1.7.6

### ISSUE THREAD

**Issue by porlock** [joshp23/YOURLS-Expiry#20]
Links even when are maked green as expired still works

**Comment by joshp23** [comment]
The plugin is working as expected while running the [latest](https://github.com/YOURLS/YOURLS/commit/c43e9237005f50ded9796f5f5da058182c50dad7) commit from YOURLS master. In other words, the links will show green in the admin area _if_ that option is set on _and_ the link is set to have some sort of expiration. _After_ the link has expired it will remain listed until  
1. the link is clicked and then removed from the database or 
2. it is pruned via cron
Again, it is working as expected in my environment. Please use the [A.I.D. plugin](https://github.com/PopVeKind/admin_issue_diagnostic), post the relevant data here, and maybe I can see if there is something in your environment that might be interfering with function.

**Comment by porlock** [comment]
Hey, this is A.I.D plugin output 

- YOURLS version: 1.7.7
- Plugins enabled:
    1. expiry/plugin.php
    1. random-shorturls/plugin.php
    1. admin_issue_diagnostic/plugin.php
- YOURLS DB Ver: 482
- PHP version: 7.3.11
- Server OS Build: Linux
- Server & version: Apache
- Browser information: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

- Generated by the AID Plugin ver 1.0

I have a YOURLS installed in subdriectory, 

## Bug description

### What is the current behavior?
1) I can't set up default expire behavior.
2) link does not  expire when threshold is breathed. 
3) I don't see any links in  "Expiry list"
### What is the expected or desired behavior?
1) default settings affect new created links
2) link expire when threshold is breathed
3) link appears in "Expiry list"

## Reproducible bug summary steps
0. Enable following plugins
    a) expiry/plugin.php
    b) random-shorturls/plugin.php
1. Go to Manage Plugins/Expiry/Config
2. Set a Default Expiry Type to "click counter" and Default Click Counter Value to "2"
3. Go to "Admin interface" notice that "Short Link Expiration Type" is set to none
4. Manually add a link for shortening, change Short Link Expiration Type to "click counter",  Click Counter Value to "2" generate shot url.
5. Go to Plugins/Expiry/Expiry list notice that list is empty
6. Open short URL it in incognito windows 4 times, every time close browser window.
7. Notice that link still works

**Comment by joshp23** [comment]
Please set default expiry to `none` and attempt to test the plugin again.

**Comment by joshp23** [comment]
I can verify that setting a default expiry condition does nothing. So there's a bug. 

However, when I manually added expiry criteria to the link, it did set appropriately, and the link expired as expected. So, I cannot reproduce that bug.

**Comment by porlock** [comment]
Josh, it seams that it sometimes works and sometimes not, when you don't have any links in your database and add initial one it doesn't but when i tried before with some links existing it seams works.

**Comment by joshp23** [comment]
Well, I cannot get default expiry data to set at all as is. With or without links in the database, after adding a link with expiry conditions, they expire as expected. You will have to help me with exact conditions for when they do not expire. 

Note: I was careful to use different containers in Firefox every time I attempted a short URL. Or, a new private session every click.

**Comment by joshp23** [comment]
Please see https://github.com/joshp23/YOURLS-Expiry/commit/744cbc4d537d81353a71f3da7dd88c4c8812c9fb as this should fix (at least a part) of your issue.

**Comment by porlock** [comment]
Hi Josh
yes issue with default values looks solved, but for me whole plugin works pretty much randomly, and mostly does not at all :( 
please check this movie https://youtu.be/t2sYJu9zISw

**Comment by joshp23** [comment]
I find that particularly odd. If it is truly random, then there is likely something in your environment that is causing the problem. Links not taking expiry data, or links not expiring when expected, I need to be able to reproduce the behavior in order to squash the bug. Try to isolate the behavior so that you can reliably predict when it will and won't work, then we can squash it.

**Comment by porlock** [comment]
It is probably not random, i just can find any pattern that cause that :( , but in my case it works wrongly in 80% of time. I will try to figure out it.

**Comment by shrimpchip28** [comment]
I am having the same issues as @porlock  I downgraded Yourls from 1.7.9 to 1.7.3 just to test. The video he provided is exactly what I am experiencing. Values are not inserted properly into the DB. I've tried on Firefox and Brave. My site is hosted on hostinger.

**Comment by joshp23** [comment]
b4ca98b349a0c5c97f77c674023c770e0a2edefb which is in the latest release [2.2.0](https://github.com/joshp23/YOURLS-Expiry/releases/tag/2.2.0) should address this. Please review the README for a note on upgrading.

I am running 2.2.0 with YOURLS 1.7.10 https://github.com/YOURLS/YOURLS/commit/cab0c150a0ce2b0f8775a029c6b47fa98d69598b and everything is working fine.
