### ISSUE TITLE
Plugin does not work at all

### ISSUE THREAD

**Issue by porlock** [joshp23/YOURLS-Expiry#22]
My last ticket was closed without any investigation, i have latest version of plugin nad yourls and it odes not work at all. This time you can find all my files and database in attachment co you can easy recreate the issue.
[baza_yourls.sql.gz](https://github.com/joshp23/YOURLS-Expiry/files/4272549/baza_yourls.sql.gz)
[china-shop.pl.tar.gz](https://github.com/joshp23/YOURLS-Expiry/files/4272550/china-shop.pl.tar.gz)

**Comment by joshp23** [comment]
I did investigate, and I found that this plugin works as expected with the latest code on my server. I recommended a course of action so that I could help debug the situation, and you ignored it and opened this issue instead. I'm closing this, refer to the other issue.

**Comment by porlock** [comment]
sorry for that, you right.. i miss this that is probably because im lite seek right now, i will use a A.I.D. plugin and will update initial ticket.

**Comment by joshp23** [comment]
Indeed, I've been sick for the last 4 weeks! Feel better!
