### ISSUE TITLE
Enhancement : easier git pull

### ISSUE THREAD

**Issue by NewRedsquare** [joshp23/YOURLS-Expiry#23]
Hello,

I really appreciate your work !
The only small "problem", is that i must manually git pull and move files for every update. Actually, i have 20 plugins installed. The rest of plugins are automatically git-pulled without manual files-moving.

I hope you understood it,

NewRedsquare.

**Comment by joshp23** [comment]
I do understand what you're request is, and why it might be desirable. Unfortunately I won't be making this change at this time. Sorry.
