### ISSUE TITLE
Expire immediately (feature request)

### ISSUE THREAD

**Issue by drbeco** [joshp23/YOURLS-Expiry#32]
Dear Josh,

After having my site blocked 3 times, and getting warning emails from my host and google, and each time adding more and more security plugins, I'm searching for desperate measures.

I even blacklisted ALL ranges of IP with a plugin with the same name, from 0.0.0.0 to 255.255.255.255 and still got new short links added pointing to phishing places.

I wonder if we could add a "expire immediately" option to all links that are added. I do not use the shortener too much, so it is ok for me to turn off the option before I add a valid link, and then turn it on again to let the page rest in peace for a while.

Thanks

**Comment by joshp23** [comment]
As far as changing this code to solve your problem, probably not. I would encourage you to look for any security hole you may have left open, try the YOURLS forums for this one. 

However, you can set the default expiry type to "Clock" and then set the minimal time allowed. I don't advise it. It's putting a band-aid where stitches are needed.
