### ISSUE TITLE
Keywords Randomised in Table

### ISSUE THREAD

**Issue by lmizz92** [joshp23/YOURLS-Expiry#33]
Hi,

I have encountered an issue when adding a time counter to new links since on the YOURLS admin interface is for example "testing", in the keyword field in the expiry table is "0x74657374000000000000000000000000000". I have dropped the table and reinstalled the table and disabled other plugins to see if they effecting, but to no avail, keyword kept being a couple of numbers followed by a lot zeros. No errors are displayed when adding with debug set to true, therefore the link never expires and still is accessible after expiration.

What might be causing this pls?

Currently using YOURLS ver 1.8.1 and Expiry plugin ver 2.4.1

**Comment by joshp23** [comment]
To clarify, you are attempting to add a `Clock` type expiry to a link via the admin area and the resulting value in the `Timer` column of the expiry table appears as  `0x74657374000000000000000000000000000`. You have tried to drop the database and the behavior remains. Is that right?

**Comment by lmizz92** [comment]
Not exactly. I have these columns in the expiry table (keyword | type | click | timestamp | shelflife | postexpire) and the keyword column is being filled up with 0x74657374000000000000000000000000000, therefore if there is a column with the specific name of "Timer", it is not being created. I have tried dropping the expiry table and creating it again but the same issue occurs.

![image](https://user-images.githubusercontent.com/80838880/112156629-b62be100-8be6-11eb-9fa9-7ab286823a40.png)

**Comment by lmizz92** [comment]
Is there an update regarding this? What could be causing this, please?

**Comment by joshp23** [comment]
I have been busy with my 9 to 5 and have not had an.opportunity to look into this. I might have some time this weekend to see if I can reproduce the error.

**Comment by lmizz92** [comment]
> I have been busy with my 9 to 5 and have not had an.opportunity to look into this. I might have some time this weekend to see if I can reproduce the error.

Thanks very much for the response back. Appreciated.

**Comment by Omniru** [comment]
This may be the same issue:
[https://github.com/joshp23/YOURLS-Expiry/issues/35#issuecomment-861717223](https://github.com/joshp23/YOURLS-Expiry/issues/35#issuecomment-861717223)

**Comment by lmizz92** [comment]
Hi @Omniru,

Thanks for the thread, I was able to solve the issue.

Regards
