### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by beceha** [joshp23/YOURLS-Expiry#4]
Activating the plugin causes a fatal error:

`Fatal error: Uncaught Error: Call to undefined method ezSQL_pdo_YOURLS::fetchAffected() in /www/htdocs/w0000000/my-site.de/empfiehlt/user/plugins/expiry/plugin.php:1400 Stack trace: #0 /www/htdocs/w0000000/my-site.de/empfiehlt/includes/functions-plugins.php(152): expiry_activated(Array) #1 /www/htdocs/w0000000/my-site.de/empfiehlt/includes/functions-plugins.php(191): yourls_apply_filter('activated_expir...', Array) #2 /www/htdocs/w0000000/my-site.de/empfiehlt/includes/functions-plugins.php(491): yourls_do_action('activated_expir...') #3 /www/htdocs/w0000000/my-site.de/empfiehlt/admin/plugins.php(25): yourls_activate_plugin('expiry/plugin.p...') #4 {main} thrown in /www/htdocs/w0000000/my-site.de/empfiehlt/user/plugins/expiry/plugin.php on line 1400`

**YOURLS:** 1.7.2 + code change [from here](https://github.com/YOURLS/YOURLS/commit/dd78d7f226017b8dbba4f2e9ee4baafe759a7dee)
**Plugin Expiry:** latest
**PHP:** 7.1.11

Any idea please?
Thanks

**Comment by joshp23** [comment]
This plugin requires 1.7.3, not 1.7.2 + that code change.

Looking at your error it appears to be a pdo (sql/database driver) issue.

You can go back to a pre-PDO version of this plugin (not recommended) OR upgrade to thr latest YOURLS. . . 1.7.3 with a pull from git

**Comment by beceha** [comment]
Thanks, but where is a YOURLS 1.7.3?
the latest is 1.7.2:
https://github.com/YOURLS/YOURLS/releases
AND (!) I have added this fix:
https://github.com/YOURLS/YOURLS/commit/dd78d7f226017b8dbba4f2e9ee4baafe759a7dee

**Comment by joshp23** [comment]
please refer to my comment above which notes..

>  upgrade to thr latest YOURLS. . . 1.7.3 with a pull from git
