### ISSUE TITLE
Wrong icon paths when installed in a subdirectory

### ISSUE THREAD

**Issue by beceha** [joshp23/YOURLS-Expiry#5]
There is a wrong path for the settings page's icons of YOURLS-Expiry, when YOURLS is installed in a subdirectory.

The icon for "remove expiry" and the icon for "Strip postx" is missing due to wrong paths:

Screenshot:
https://i.imgur.com/NfqJnXf.png

Graphic Info from browser:
https://i.imgur.com/mp3bh4X.png

For example the path for the YOURLS logo is:
`https://mysite.de/empfiehlt/images/yourls-logo.png`

But the paths of the "Expiry" settings page icons is:
`https://mysite.de/images/delete.png`

"empfiehlt" is my subdirectory for the YOURLS installation, which is missing in the icon's path of Expiry plugin.

YOURLS 1.7.3
PHP 7.1.11
Browser: Firefox 61.0.1 Desktop

**Comment by joshp23** [comment]
Sure, I can have a go at that later, when I have time. I am open to pull requests ;)

**Comment by joshp23** [comment]
latest commit should fix it

**Comment by beceha** [comment]
Yes, great, thanks a lot!

**Comment by joshp23** [comment]
go ahead and update. I fixed a critical bug where expired links weren't expiring.
