### ISSUE TITLE
Can't set default expiry type

### ISSUE THREAD

**Issue by 7daysofrain** [joshp23/YOURLS-Expiry#6]
Hello,

I try to change the default expiry type in the config section. Select in the dropdown "timer" or "click counter" and hit Submit. No error is showed by the drop down appears in "none" again and when i create a new link not default expiry is set.

Thanks

**Comment by joshp23** [comment]
look in your database, the option should be set. It's a display issue

**Comment by joshp23** [comment]
fixed in latest release with this https://github.com/joshp23/YOURLS-Expiry/commit/2beb45fb32890c5c4cfa4c30b8f64cc678169283

**Comment by 7daysofrain** [comment]
thanks for the quick response and for developing this plugin :)
