### ISSUE TITLE
Reserved Words (Example "mod")

### ISSUE THREAD

**Issue by JamoCA** [joshp23/YOURLS-Expiry#9]
I'm a ColdFusion developer and I was passing URL parameters to an object and ran into an issue with the "`mod`" parameter.  It threw a ColdFusion error and it took me a little while to determine that the parser was treating this parameter as a "method call" instead of a "key name".

I wanted to report this issue as I've encountered this in the past when writing my own scripts.  I now take extra measures to ensure that I'm not using a reserved keyword whether I'm developing with Java, javascript, SQL, CFML, PHP, .Net, etc.   In my internal scripting, I've renamed this parameter to "ageUnit".

**Comment by joshp23** [comment]
nice catch.

**Comment by joshp23** [comment]
that last ref was a mistake ;)
